SiparisSepetim/SiparisSepetim/Models/ErrorViewModel.cs
using System;

namespace SiparisSepetim.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SiparisSepetim/SiparisSepetim/Models/ModelViewCategories.cs
using OL;
using System.Collections.Generic;

namespace SiparisSepetim.Models
{
	public class ModelViewCategories
	{
		public List<ObjCategory> Category { get; set; } = new List<ObjCategory>();

		
	}
}

SiparisSepetim/SiparisSepetim/Models/ModelViewProducts.cs
using OL;
using System.Collections.Generic;

namespace SiparisSepetim.Models
{
    public class ModelViewProducts
    {
        public List<ObjProduct> Product { get; set; } = new List<ObjProduct>();

        public List<ObjCategory> Categories { get; set; } = new List<ObjCategory>();
    }
}

SiparisSepetim/SiparisSepetim/Models/ModelViewUsers.cs
using OL;
using System.Collections.Generic;

namespace SiparisSepetim.Models
{
    public class ModelViewUsers
    {
        public ObjUser User { get ; set; } = new ObjUser();

    }
}

SiparisSepetim/SiparisSepetim/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OL;
using System;
namespace SiparisSepetim.Controllers
{
    public class CartController : Controller
    {
        
        public IActionResult Index()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Index(ObjProduct obj)
        {

            return View();
        }
    }
}

SiparisSepetim/SiparisSepetim/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using SiparisSepetim.Models;


namespace SiparisSepetim.Controllers
{
    public class CategoryController : Controller
    {
        
        public IActionResult Index()
        {
            Models.ModelViewCategories model = new ModelViewCategories();
            BL.CategoryManager _categoryManager = new BL.CategoryManager();

            model.Category = _categoryManager.GetCategories();
            

            //View İçine gönderiliyor
            return View(model);
        }
    }
}

SiparisSepetim/SiparisSepetim/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SiparisSepetim.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SiparisSepetim.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            //BL.CategoryManager categoryManager = new BL.CategoryManager();
            //categoryManager.GetCategories();
            //ViewBag.data = categoryManager.GetCategories();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SiparisSepetim/SiparisSepetim/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OL;
using SiparisSepetim.Models;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace SiparisSepetim.Controllers
{
   
    public class LoginController : Controller
    {
        BL.UserManager _userManager = new BL.UserManager();


        public IActionResult Index()
        {
                return View();
        }

        
        public IActionResult Submit(Models.ModelViewUsers model)  //ModelViewUserın içinden ObjDbUser daki mail ve şifreyi çekiyor.
        {

            var bilgiler = _userManager.Getlogin(model.User.eMail, model.User.pass);

            //ClaimsIdentity identity = new ClaimsIdentity((bilgiler, CookieAuthenticationDefaults.AuthenticationScheme);
            //ClaimsPrincipal principal = new ClaimsPrincipal(identity);
            if (bilgiler.UserId > 0) // Tabloda böyle bir User var mı
            {
                
                HttpContext.Session.SetString("UserId", bilgiler.UserId.ToString()); //Liste oluştururken hangi kullanıcının id si ile oluştuğu
                //HttpContext.SignInAsync(principal, new AuthenticationProperties() { IsPersistent = true });
                return RedirectToAction("Index", "OrderList" );
            }
            else
                return RedirectToAction("Index", "Login");

      
        }

        
        
        
            

           
        

    }
}

SiparisSepetim/SiparisSepetim/Controllers/OrderListController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using OL;
using System;

namespace SiparisSepetim.Controllers
{
    public class OrderListController : Controller
    {
        BL.OrderListManager _orderListManager = new BL.OrderListManager();  // Manager içindeki fonksiyonları kullanabilmek için
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost] 
        public IActionResult Index(ObjOrderList model) //ObjOrderListteki properertyleri girdi olarak alıyor
        {
            model.UserId = Int32.Parse(HttpContext.Session.GetString("UserId"));
            _orderListManager.SetOrderList(model);

            if (model.UserId > 0)
            {
                return RedirectToAction("Index", "Product");
            }
            else
                return RedirectToAction("Index", "OrderList");
            
        }
    }
}

SiparisSepetim/SiparisSepetim/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using OL;
using System;

namespace SiparisSepetim.Controllers
{
    public class ProductController : Controller
    {


        
        public IActionResult Index()
        {   

            BL.ProductManager _ProductManager = new BL.ProductManager();
            BL.CategoryManager _CategoryManager=new BL.CategoryManager();
            Models.ModelViewProducts model = new Models.ModelViewProducts();

             
            model.Product = _ProductManager.GetProducts(); // Tüm ürünleri getiri
            /*  model.List = manager.GetList();*/ // Ürünler arasında kategoriye göre listelemek için 
            model.Categories = _CategoryManager.GetCategories();
            //View İçine gönderiliyor
            return View(model);
        }

        //public IActionResult List(string categoryName)
        //{
        //    BL.ProductManager _ProductManager = new BL.ProductManager();
        //    Models.ModelViewProducts model = new Models.ModelViewProducts();
        //    model.Product = _ProductManager.GetProducts();
        //    return View("Index", model);
        //}

    }
}

SiparisSepetim/SiparisSepetim/Controllers/SignController.cs
using Microsoft.AspNetCore.Mvc;

namespace SiparisSepetim.Controllers
{
    public class SignController : Controller
    {
        BL.UserManager _userManager = new BL.UserManager();
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(OL.ObjUser model) // Ol.Db.ObjUser sınıfından nesne oluşturdum ve kayıt nesnesi sign formundan verileri tuttu.
        {
            _userManager.SetSign(model);
            return View();
        }
    }
}

SiparisSepetim/SiparisSepetim/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;

namespace SiparisSepetim.Controllers
{
    public class UsersController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }
    }
}

SiparisSepetim/SiparisSepetim/Views/Cart/Index.cshtml
<div class="container-fluid">
            <div class="page-header">
              <div class="row">
                <div class="col-sm-6">
                  <div class="page-header-left">
                    <h3>Cart</h3>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
            </div>
          </div>
           <!-- Container-fluid starts-->
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-12">
                <div class="card">
                  <div class="card-header pb-0">
                    <h5>Cart</h5>
                  </div>
                  <div class="card-body">
                    <div class="row">
                      <div class="order-history table-responsive wishlist">
                        <table class="table table-bordered">
                          <thead>
                            <tr>
                              <th>Prdouct</th>
                              <th>Prdouct Name</th>
                              <th>Price</th>
                              <th>Quantity</th>
                              <th>Action</th>
                              <th>Total</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td><img class="img-fluid img-40" src="/assets/images/product/1.png" alt="#"></td>
                              <td>
                                <div class="product-name"><a href="#"> 
                                    <h6>Long Top</h6></a></div>
                              </td>
                              <td>$21</td>
                              <td>
                                <fieldset class="qty-box">
                                  <div class="input-group">
                                    <input class="touchspin text-center" type="text" value="5">
                                  </div>
                                </fieldset>
                              </td>
                              <td><i></i></td>
                              <td>$12456</td>
                            </tr>
                            <tr>
                              <td colspan="4">                                           

                              </td>
                              <td class="total-amount">
                                <h6 class="m-0 text-end"><span class="f-w-600">Total Price :</span></h6>
                              </td>
                              <td><span>$6935.00  </span></td>
                            </tr>
                            <tr>
                              <td class="text-end" colspan="5"><a class="btn btn-secondary cart-btn-transform" asp-action="Index" asp-controller="Product">continue shopping</a></td>
                              <td><a class="btn btn-success cart-btn-transform">check out</a></td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Container-fluid Ends-->

SiparisSepetim/SiparisSepetim/Views/Login/Index.cshtml
@model SiparisSepetim.Models.ModelViewUsers

@{
	//Layout = "~/Views/Shared/_Layout.cshtml";
	Layout = "";
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="viho admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
	<meta name="keywords" content="admin template, viho admin template, dashboard template, flat admin template, responsive admin template, web app">
	<meta name="author" content="pixelstrap">
	<link rel="icon" href="../assets/images/favicon.png" type="image/x-icon">
	<link rel="shortcut icon" href="../assets/images/favicon.png" type="image/x-icon">
	<title>viho - Premium Admin Template</title>
	<!-- Google font-->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap" rel="stylesheet">
	<!-- Font Awesome-->
	<link rel="stylesheet" type="text/css" href="/assets/css/fontawesome.css">
	<!-- ico-font-->
	<link rel="stylesheet" type="text/css" href="/assets/css/icofont.css">
	<!-- Themify icon-->
	<link rel="stylesheet" type="text/css" href="/assets/css/themify.css">
	<!-- Flag icon-->
	<link rel="stylesheet" type="text/css" href="/assets/css/flag-icon.css">
	<!-- Feather icon-->
	<link rel="stylesheet" type="text/css" href="/assets/css/feather-icon.css">
	<!-- Plugins css start-->
	<!-- Plugins css Ends-->
	<!-- Bootstrap css-->
	<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.css">
	<!-- App css-->
	<link rel="stylesheet" type="text/css" href="/assets/css/style.css">
	<link id="color" rel="stylesheet" href="/assets/css/color-1.css" media="screen">
	<!-- Responsive css-->
	<link rel="stylesheet" type="text/css" href="/assets/css/responsive.css">
</head>
<body>
	<!-- Loader starts-->
	<div class="loader-wrapper">
		<div class="theme-loader">
			<div class="loader-p"></div>
		</div>
	</div>
	<!-- Loader ends-->
	<!-- page-wrapper Start-->
	<section>
		<div class="container-fluid p-0">
			<div class="row">
				<div class="col-12">
					<div class="login-card">


						@using (Html.BeginForm("Submit", "Login", FormMethod.Post, new { @class = "theme-form login-form", id = "postFormSeo", enctype = "multipart/form-data" }))
						{
							<h4>Login</h4>
							<h6>Welcome back! Log in to your account.</h6>
							<div class="form-group">
								<label>Email Address</label>

								<div class="input-group">
									<span class="input-group-text"><i class="icon-email"></i></span>
									@Html.TextBoxFor(m=>m.User.eMail,new {@class="form-control" ,@type="email",@required="",@placeholder="Test@gmail.com"})

								</div>
							</div>
							<div class="form-group">
								<label>Password</label>
								<div class="input-group">
									<span class="input-group-text"><i class="icon-lock"></i></span>
									@Html.TextBoxFor(m=>m.User.pass,new {@class="form-control" ,@type="password",@required="",@placeholder="*********"})
									<div class="show-hide"><span class="show">                         </span></div>
								</div>
							</div>
							<div class="form-group">
							</div>
							<div class="form-group">
								<button class="btn btn-primary btn-block" type="submit">Sign in</button>
							</div>
							<div class="login-social-title">
								<h5>Sign in with</h5>
							</div>

							<p>Don't have account?<a asp-action="Index" asp-controller="Sign">Create Account</a></p>


						}


					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- page-wrapper end-->
	<!-- latest jquery-->
	<script src="/assets/js/jquery-3.5.1.min.js"></script>
	<!-- feather icon js-->
	<script src="/assets/js/icons/feather-icon/feather.min.js"></script>
	<script src="/assets/js/icons/feather-icon/feather-icon.js"></script>
	<!-- Sidebar jquery-->
	<script src="/assets/js/sidebar-menu.js"></script>
	<script src="/assets/js/config.js"></script>
	<!-- Bootstrap js-->
	<script src="/assets/js/bootstrap/popper.min.js"></script>
	<script src="/assets/js/bootstrap/bootstrap.min.js"></script>
	<!-- Plugins JS start-->
	<!-- Plugins JS Ends-->
	<!-- Theme js-->
	<script src="/assets/js/script.js"></script>
	<!-- login js-->
	<!-- Plugin used-->
</body>
</html>

SiparisSepetim/SiparisSepetim/Views/OrderList/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@



		<form  asp-action="Index" asp-controller="OrderList" method="post">

		<label>Lütfen Oluşturacağınız Listenin ismini giriniz:</label>
		 <div class="small-group">
		 <div class="input-group"><span class="input-group-text"><i class="icon-shopping-cart"></i></span>
			<input class="form-control" type="text" required="" placeholder="Benim Listem" name="OrderListname"/>
		 </div>
		 </div >
		 <div class="form-group">
			<button class="btn btn-primary btn-block" type="submit">Listemi ekle</button>
		 </div>

		</form>

SiparisSepetim/SiparisSepetim/Views/Product/Index.cshtml
@model SiparisSepetim.Models.ModelViewProducts

@{
    ViewData["Title"] = "Home Page";

} 
  <div class="container-fluid">
            <div class="page-header">
              <div class="row">
                <div class="col-sm-6">
                  <h3>Product</h3>

                </div>
                    @foreach (var item in Model.Categories)
                   {
                         <ul>
                              <li><a class="nav-link menu-title link-nav"> <span>@item.categoryName</span></a></li>	
                         </ul>
                   }           
              </div>
            </div>
          </div>
          <!-- Container-fluid starts-->
          <div class="container-fluid product-wrapper">
            <div class="product-grid">
              <div class="feature-products">
                <div class="row m-b-10">
                  <div class="col-md-3 col-sm-2 products-total">
                    <div class="square-product-setting d-inline-block"><a class="icon-grid grid-layout-view" href="javascript:void(0)" data-original-title="" title=""><i data-feather="grid"></i></a></div>
                    <div class="square-product-setting d-inline-block"><a class="icon-grid m-0 list-layout-view" href="javascript:void(0)" data-original-title="" title=""><i data-feather="list"></i></a></div>
                    <div class="d-none-productlist filter-toggle">
                      <h6 class="mb-0">Filters<span class="ms-2"><i class="toggle-data" data-feather="chevron-down"></i></span></h6>
                    </div>
                    <div class="grid-options d-inline-block">
                      <ul>
                        <li><a class="product-2-layout-view" href="javascript:void(0)" data-original-title="" title=""><span class="line-grid line-grid-1 bg-primary"></span><span class="line-grid line-grid-2 bg-primary"></span></a></li>
                        <li><a class="product-3-layout-view" href="javascript:void(0)" data-original-title="" title=""><span class="line-grid line-grid-3 bg-primary"></span><span class="line-grid line-grid-4 bg-primary"></span><span class="line-grid line-grid-5 bg-primary"></span></a></li>
                        <li><a class="product-4-layout-view" href="javascript:void(0)" data-original-title="" title=""><span class="line-grid line-grid-6 bg-primary"></span><span class="line-grid line-grid-7 bg-primary"></span><span class="line-grid line-grid-8 bg-primary"></span><span class="line-grid line-grid-9 bg-primary"></span></a></li>
                        <li><a class="product-6-layout-view" href="javascript:void(0)" data-original-title="" title=""><span class="line-grid line-grid-10 bg-primary"></span><span class="line-grid line-grid-11 bg-primary"></span><span class="line-grid line-grid-12 bg-primary"></span><span class="line-grid line-grid-13 bg-primary"></span><span class="line-grid line-grid-14 bg-primary"></span><span class="line-grid line-grid-15 bg-primary"></span></a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="col-md-9 col-sm-10 text-end"><span class="f-w-600 m-r-5"></span>
                    <div class="select2-drpdwn-product select-options d-inline-block">
                      <select class="form-control btn-square" name="select">
                      </select>
                    </div>
                  </div>
                </div>
                <div class="row">                            
                  
                  </div>
                </div>
              </div>
              </div>
              <div class="product-wrapper-grid">
                <div class="row">
                   @{
                       foreach (var product in Model.Product)
                       {
                           <div class="col-xl-3 col-sm-6 xl-4">
                            <div class="card">
                              <div class="product-box">
                                <div class="product-img"><img class="img-fluid" src="/assets/images/ecommerce/01.jpg" alt="">
                                  <div class="product-hover">
                                    <ul>
                                      <li><a asp-action="Index" asp-controller="Cart"><i class="icon-shopping-cart"></i></a></li>
                                      <li><a data-bs-toggle="modal" data-bs-target="#exampleModalCenter16"><i class="icon-eye"></i></a></li>
                                    </ul>
                                  </div>
                                </div>
                                <div class="modal fade" id="exampleModalCenter16">
                                  <div class="modal-dialog modal-lg modal-dialog-centered">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <div class="product-box row">
                                          <div class="product-img col-lg-6"><img class="img-fluid" src="/assets/images/ecommerce/01.jpg" alt=""></div>
                                          <div class="product-details col-lg-6 text-start"><a>
                                              <h4>@product.productName - @product.category.categoryName</h4></a>
                                            <div class="product-price">$@product.price
                                              <del>$@(product.price * 3/10)</del>
                                            </div>
                                            <div class="product-view">
                                              <h6 class="f-w-600">Product Details</h6>
                                              <p class="mb-0">Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo.</p>
                                            </div>
                 
                                            </div>
                                            <div class="product-qnty">
                                              <h6 class="f-w-600">Quantity</h6>
                                              <fieldset>
                                                <div class="input-group">
                                                  <input class="touchspin text-center" type="text" value="5">
                                                </div>
                                              </fieldset>
                                              <form  asp-action="Index" asp-controller="Cart" method="post" class="addcart-btn">
                                              <div ><a class="btn btn-primary me-3" >Add to Cart name="@product.productName"</a><a class="btn btn-primary">View Details</a></div>
                                              </form>
                                              </div>
                                          </div>
                                        </div>
                                        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div class="product-details"><a href="product-page.html">
                                    <h4>@product.productName</h4></a>
                                  <div class="product-price">$@product.price
                                    <del>$@(product.price * 3/2)</del>
                                  </div>
                                </div>
                              </div>
                            </div>                        
                       }  
                  }
                  
                </div>
              </div>
            
          
          <!-- Container-fluid Ends-->

SiparisSepetim/SiparisSepetim/Views/Sign/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    Layout = "";
}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="viho admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, viho admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="../assets/images/favicon.png" type="image/x-icon">
    <link rel="shortcut icon" href="../assets/images/favicon.png" type="image/x-icon">
    <title>viho - Premium Admin Template</title>
    <!-- Google font-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap" rel="stylesheet">
    <!-- Font Awesome-->
    <link rel="stylesheet" type="text/css" href="/assets/css/fontawesome.css">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="/assets/css/icofont.css">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="/assets/css/themify.css">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="/assets/css/flag-icon.css">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="/assets/css/feather-icon.css">
    <!-- Plugins css start-->
    <link rel="stylesheet" type="text/css" href="/assets/css/sweetalert2.css">
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.css">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="/assets/css/style.css">
    <link id="color" rel="stylesheet" href="/assets/css/color-1.css" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="/assets/css/responsive.css">
  </head>
  <body>
    <!-- Loader starts-->
    <div class="loader-wrapper">
      <div class="theme-loader">    
        <div class="loader-p"></div>
      </div>
    </div>
    <!-- Loader ends-->
    <!-- page-wrapper Start-->
    <section>         
      <div class="container-fluid p-0"> 
        <div class="row m-0">
          <div class="col-12 p-0">    
            <div class="login-card">
              

                
                <form  asp-action="Index" asp-controller="Sign" method="post" class="theme-form login-form">

                <h4>Create your account</h4>
                <h6>Enter your personal details to create account</h6>

                <div class="form-group">
                  <label>Your Name</label>
                  <div class="small-group">
                    <div class="input-group"><span class="input-group-text"><i class="icon-user"></i></span>
                      <input class="form-control" type="text" required="" placeholder="Fist Name" name="name"/>
                    </div>
                    <div class="input-group"><span class="input-group-text"><i class="icon-user"></i></span>
                      <input class="form-control" type="text" required="" placeholder="Last Name" name="surname"/>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label>Email Address</label>
                  <div class="input-group"><span class="input-group-text"><i class="icon-email"></i></span>
                    <input class="form-control" type="email" required="" placeholder="Test@gmail.com" name="eMail"/>
                  </div>
                </div>
                <div class="form-group">
                  <label>Password</label>
                  <div class="input-group"><span class="input-group-text"><i class="icon-lock"></i></span>
                    <input class="form-control" type="password" required="" placeholder="*********" name="pass"/>
                    <div class="show-hide"><span class="show"></span></div>
                  </div>
                </div>
                <div class="form-group">
                  <button class="btn btn-primary btn-block" type="submit" >Create Account</button>
                </div>

                
                <div class="login-social-title">                
                  <h5>signup with</h5>
                </div>
                <div class="form-group">
               
                </div>
                <p>Already have an account?<a class="ms-2" asp-action="Index" asp-controller="Login">Sign in</a></p>
                </form>
              
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- page-wrapper end-->
    <!-- latest jquery-->
    <script src="/assets/js/jquery-3.5.1.min.js"></script>
    <!-- feather icon js-->
    <script src="/assets/js/icons/feather-icon/feather.min.js"></script>
    <script src="/assets/js/icons/feather-icon/feather-icon.js"></script>
    <!-- Sidebar jquery-->
    <script src="/assets/js/sidebar-menu.js"></script>
    <script src="/assets/js/config.js"></script>
    <!-- Bootstrap js-->
    <script src="/assets/js/bootstrap/popper.min.js"></script>
    <script src="/assets/js/bootstrap/bootstrap.min.js"></script>
    <!-- Plugins JS start-->
    <script src="/assets/js/sweet-alert/sweetalert.min.js"></script>
    <!-- Plugins JS Ends-->
    <!-- Theme js-->
    <script src="/assets/js/script.js"></script>
    <!-- login js-->
    <!-- Plugin used-->
  </body>
</html>